export const data = [
  {
    title: 'Fabine Exklusiv dreamlike Jeanswindel',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/buntewindel/8865/fabine-exklusiv-dreamlike-jeanswindel-blau-medium-einzelstueck?number=MD-1',
    picture: 'fabineekslusivdreamlikejeanswindel.jpg',
    properties: [
      { name: 'Typ Povrchu', value: 'Plastový' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 4 },
      { name: 'Absorpcia', value: 4, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 2, type: 'rating', icon: '⭐️' },
      { name: 'Pohodlie', value: 2, type: 'rating', icon: '🛏' },
      { name: 'Tvrdosť', value: 'Tvrdá' },
      { name: 'Výsteľka', value: 'Tvrdá' },
    ],
    pattern: 'Modré Džínsy',
    notes: [
      'Prvé nosenie bolo v pohode s hmotnosťou 751g a 3 pocikaniami. Počas nosenia sa však rozopla spodná páska. Dali sa však viackrát znovu prilepiť, takže nebolo treba ani dodatočnej pásky ako používame pri iných plienkach.',
      'Druhé nosenie bolo už lepšie. 5 pomočení s váhou 1075g. Páska sa taktiež raz samovoľne rozlepila ale plienka zatiaľ bezproblémov drží. Neabsovuje však takmer vôbec odór a behom 12 h je už moč cítiť.',
      'Tretie nosenie, 5 pomočení s váhou 1075g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Je pravda však, že moč stále cítiť a pri piatom pocikaní, je dobré už mať dobre tesniace PVC nohavičky nakoľko už začína pretekať z bokov.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
    ],
  },
  {
    title: 'Seguna Slip Plus',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/sensilind-seguna/9363/seguna-slip-plus-medium-einzelstueck',
    picture: 'segunaslipplus.jpg',
    properties: [
      { name: 'Typ Povrchu', value: 'Priedušný' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 2 },
      { name: 'Absorpcia', value: 3, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 4, type: 'rating', icon: '⭐️' },
      { name: 'Pohodlie', value: 5, type: 'rating', icon: '🛏' },
      { name: 'Tvrdosť', value: 'Veľmi Mäkká' },
      { name: 'Výsteľka', value: 'Makká' },
    ],
    pattern: 'Biele so žltým prúžkom',
    notes: [
      'Vzhľadom na priedušnosť je veľké odporúčanie nosiť aj ochranné PVC nohavičky.',
      'Sú diskrétne a tak sú veľmi vhodné na denné nosenie.',
      'Bez problémov sa dajú použiť na minimálne 3 pocikania',
      'S opakovaným zalepením väčšinou nebol problém (suchý zips), v niektorých prípadoch však je potrebné si už pomôcť aj páskou (v prípade mnohonásobého prelepovania)',
    ],
  },
  {
    title: 'Seguna Slip Maxi',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/sensilind-seguna/9359/seguna-slip-maxi-medium-gruen/weiss-einzelstueck',
    picture: 'segunaslipmaxi.jpg',
    properties: [
      { name: 'Typ Povrchu', value: 'Priedušný' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 1 },
      { name: 'Absorpcia', value: 6, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 5, type: 'rating', icon: '⭐️' },
      { name: 'Pohodlie', value: 4, type: 'rating', icon: '🛏' },
      { name: 'Tvrdosť', value: 'Veľmi Mäkká' },
      { name: 'Výsteľka', value: 'Makká' },
    ],
    pattern: 'Biele so zeleným prúžkom',
    notes: [
      'Bez problémov sa dajú použiť na minimálne 6 pocikaní',
      'Vzhľadom na priedušnosť je veľké odporúčanie nosiť aj ochranné PVC nohavičky.',
      'Nie sú príliš diskrétne a tak sú veľmi na nosenie kde je treba dlhá výdrž a sú k dispozícii PVC nohavičky (je hrubá).',
      'S opakovaným zalepením väčšinou nebol problém (suchý zips), v niektorých prípadoch však je potrebné si už pomôcť aj páskou (v prípade mnohonásobého prelepovania)',
      'Zvládla 7 pomočení pri druhom teste. Váha plienky bola 1,887 kg. Samozrejme, že bola úplne celá mokrá, oblečenie na plienke by tak bolo úplne premočené ale gumové nohavičky k tomu pomáhajú a tak oblečenie zostáva suché a plienka drží aj pri tomto počte pomočení.',
    ],
  },
  {
    title: 'Bambino Teddy V2',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/sensilind-seguna/9359/seguna-slip-maxi-medium-gruen/weiss-einzelstueck',
    picture: 'teddy_v2.jpg',
    properties: [
      { name: 'Typ Povrchu', value: 'Plastový' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 1 },
      { name: 'Absorpcia', value: 3, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 3, type: 'rating', icon: '⭐️' },
      { name: 'Pohodlie', value: 2, type: 'rating', icon: '🛏' },
      { name: 'Tvrdosť', value: 'Veľmi Mäkká' },
      { name: 'Výsteľka', value: 'Veľmi Mäkká' },
    ],
    pattern: 'Biele s infantilným vzor medvedíkov',
    notes: ['Prvé použitie bolo na 3 pomočenia, úplne bez problémov, zápach nebol cítiť'],
  },
  {
    title: 'Sedmové hracie karty',
    link: '#',
    picture: 'karty.jpg',
    properties: [
      { name: 'Materiál', value: 'Lesklý papier' },
      { name: 'Typ kariet', value: 'Sedmové hracie karty' },
      { name: 'Počet balíkov', value: 1 },
      { name: 'Počet ks v balíku', value: 32, type: 'number' },
      { name: 'Hodnotenie zákazníkov', value: 4, type: 'rating', icon: '⭐️' },
    ],
    pattern: 'Klasické sedmové hracie karty z tvrdeného lesklého papieru',
    notes: ['Komentár od Martin: Veľmi dobre sa s nimi hrá, karty sa nelámu'],
  },
]
