export const data = [
  {
    title: 'Fabine Exklusiv dreamlike Jeanswindel',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/buntewindel/8865/fabine-exklusiv-dreamlike-jeanswindel-blau-medium-einzelstueck?number=MD-1',
    picture: 'fabineekslusivdreamlikejeanswindel.jpg',
    properties: [
      { name: 'Povrch', value: 'Plastový' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 4 },
      { name: 'Absorpcia', value: 4, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 2, type: 'rating', icon: '🌷' },
      { name: 'Pohodlie', value: 2, type: 'rating', icon: '🛌' },
      { name: 'Tvrdosť', value: 'Tvrdá' },
      { name: 'Výsteľka', value: 'Tvrdá' },
    ],
    pattern: 'Modré džínsy',
    notes: [
      'Prvé nosenie bolo v pohode s hmotnosťou 751g a 3 pocikaniami. Počas nosenia sa však rozopla spodná páska. Dali sa však viackrát znovu prilepiť, takže nebolo treba ani dodatočnej pásky ako používame pri iných plienkach.',
      'Druhé nosenie bolo už lepšie. 5 pomočení s váhou 1075g. Páska sa taktiež raz samovoľne rozlepila ale plienka zatiaľ bezproblémov drží. Neabsovuje však takmer vôbec odór a behom 12 h je už moč cítiť.',
      'Tretie nosenie, 5 pomočení s váhou 1075g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Je pravda však, že moč stále cítiť a pri piatom pocikaní, je dobré už mať dobre tesniace PVC nohavičky nakoľko už začína pretekať z bokov.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
      'Štvrté nosenie, 5 pomočení s váhou 1341g. Páska sa tentokrát ani raz samovoľne nerozlepila a plienka zatiaľ drží. Tentokrát ani nebol intenzívne cítiť moč, ale problémom bolo, že plienka sa rolovala smerom dolu (ten elastický pás by si zaslúžil vylepšienie). To sa však dá napraviť dobrými PVC nohavičkami.',
    ],
  },
  {
    title: 'Seguna Slip Plus',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/sensilind-seguna/9363/seguna-slip-plus-medium-einzelstueck',
    picture: 'segunaslipplus.jpg',
    properties: [
      { name: 'Povrch', value: 'Priedušný' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 2 },
      { name: 'Absorpcia', value: 3, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 4, type: 'rating', icon: '🌷' },
      { name: 'Pohodlie', value: 5, type: 'rating', icon: '🛌' },
      { name: 'Tvrdosť', value: 'Veľmi Mäkká' },
      { name: 'Výsteľka', value: 'Makká' },
    ],
    pattern: 'Biele so žltým prúžkom',
    notes: [
      'Vzhľadom na priedušnosť je veľké odporúčanie nosiť aj ochranné PVC nohavičky.',
      'Sú diskrétne a tak sú veľmi vhodné na denné nosenie.',
      'Bez problémov sa dajú použiť na minimálne 3 pocikania',
      'S opakovaným zalepením väčšinou nebol problém (suchý zips), v niektorých prípadoch však je potrebné si už pomôcť aj páskou (v prípade mnohonásobého prelepovania)',
    ],
  },
  {
    title: 'Seguna Slip Maxi',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/sensilind-seguna/9359/seguna-slip-maxi-medium-gruen/weiss-einzelstueck',
    picture: 'segunaslipmaxi.jpg',
    properties: [
      { name: 'Povrch', value: 'Priedušný' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 1 },
      { name: 'Absorpcia', value: 6, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 5, type: 'rating', icon: '🌷' },
      { name: 'Pohodlie', value: 4, type: 'rating', icon: '🛌' },
      { name: 'Tvrdosť', value: 'Veľmi Mäkká' },
      { name: 'Výsteľka', value: 'Makká' },
    ],
    pattern: 'Biele so zeleným prúžkom',
    notes: [
      'Bez problémov sa dajú použiť na minimálne 6 pocikaní',
      'Vzhľadom na priedušnosť je veľké odporúčanie nosiť aj ochranné PVC nohavičky.',
      'Nie sú príliš diskrétne a tak sú veľmi na nosenie kde je treba dlhá výdrž a sú k dispozícii PVC nohavičky (je hrubá).',
      'S opakovaným zalepením väčšinou nebol problém (suchý zips), v niektorých prípadoch však je potrebné si už pomôcť aj páskou (v prípade mnohonásobého prelepovania)',
      'Zvládla 7 pomočení pri druhom teste. Váha plienky bola 1,887 kg. Samozrejme, že bola úplne celá mokrá, oblečenie na plienke by tak bolo úplne premočené ale gumové nohavičky k tomu pomáhajú a tak oblečenie zostáva suché a plienka drží aj pri tomto počte pomočení.',
    ],
  },
  {
    title: 'Bambino Teddy V2',
    link: 'https://www.saveexpress.de/en/inkontinenz-einweg-disposable/windeln-pants-diapers/sensilind-seguna/9359/seguna-slip-maxi-medium-gruen/weiss-einzelstueck',
    picture: 'teddy_v2.jpg',
    properties: [
      { name: 'Povrch', value: 'Plastový' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 1 },
      { name: 'Absorpcia', value: 3, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 3, type: 'rating', icon: '🌷' },
      { name: 'Pohodlie', value: 2, type: 'rating', icon: '🛌' },
      { name: 'Tvrdosť', value: 'Veľmi Mäkká' },
      { name: 'Výsteľka', value: 'Veľmi Mäkká' },
    ],
    pattern: 'Biele s infantilným vzorom medvedíkov',
    notes: ['Prvé použitie bolo na 3 pomočenia, úplne bez problémov, zápach nebol cítiť'],
  },
  {
    title: 'Lil Squirts Splash',
    link: 'https://www.saveexpress.de/de/inkontinenz-einweg/windeln-pants-diapers/import/9365/lil-squirts-splash-windelhose-medium-einzelstueck',
    picture: 'lilsquirtssplash.jpg',
    properties: [
      { name: 'Povrch', value: 'Plastový' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 4 },
      { name: 'Absorpcia', value: 4, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 2, type: 'rating', icon: '🌷' },
      { name: 'Pohodlie', value: 2, type: 'rating', icon: '🛌' },
      { name: 'Tvrdosť', value: 'Mäkká' },
      { name: 'Výsteľka', value: 'Mäkká' },
    ],
    pattern: 'Bleldomodré so zvieratkovým motívom',
    notes: [
      'Prvé použitie bolo na 3 pomočenia, úplne bez problémov, zápach však začal byť cítiť už asi po 8h nosenia.',
      'Druhé pomočenie nebolo presne zmeranie ale mala váhu 1,2kg (1263g), opäť bol však cítiť zápach a plienka začala už aj pretekať.',
      'Tretie použitie bolo na 5 pomočení  Plienka vydržala s váhou 1kg (presne 1106g), veľmi kvalitné pásky. Má však tendiciu, keď sa elastické pásy na vrchu plienku začnú rolovať smerom dolu. Odór bol opäť výrazný.',
      'Štvrté použitie bolo na 4 pomočenia. Plienka vydržala s váhou 1,1kg (1116g). Odór bol bol pomerne intentívny.',
      'Plienku nemonžno odporučiť na dlhodobé nosenie v spoločnosti kvôli slabej absorpcii odóru. Doma to problém nerobí.',
    ],
  },
  {
    title: 'Fabine Exclusive Black',
    link: 'https://abdlfactory.com/fabine-exclusive-black-plastic-backed',
    picture: 'fabineblack.jpg',
    properties: [
      { name: 'Povrch', value: 'Plastový' },
      { name: 'Veľkosť', value: 'M' },
      { name: 'Počet testovaných ks', value: 4 },
      { name: 'Absorpcia', value: 4, type: 'rating', icon: '💧' },
      { name: 'Absorpcia odóru', value: 4, type: 'rating', icon: '🌷' },
      { name: 'Pohodlie', value: 4, type: 'rating', icon: '🛌' },
      { name: 'Tvrdosť', value: 'Mäkká' },
      { name: 'Výsteľka', value: 'Mäkká' },
    ],
    pattern:
      'Čierne s plastovým povrchom. Povrch je však trochu pórovaný, plienka je schopná mokvať, podobne ako sú tie predušné.',
    notes: [
      'Prvé testovanie bolo na 4 pomočenia. Plienka s váhou 1,4kg (1445g). Odór na tejto plienke cítiť iba už pri fakt dlhom nosení (viac ako 12h), takže jeho absorpciu beriem ako dobrú',
      'Druhé testovanie bolo použitie iba na 2 pomočenia, váha nemeraná.',
      'Tretie použitie bolo na 7 pomočení  Plienka vydržala s váhou 2,1kg (presne 2164g), ',
      '',
      'Plienka sa príliš nehodí na nosenie na verejnosti nakoľko nie je diskrétna a keďže sa dá bežne použiť na 4 pocikania, tak existujú s takovouto výdržou aj diskértnejšie plienky',
      'Plienka je trochu akoby priedušná. Dokáže pri väčšom počte pomočení pretekať nie len po stranách ale cez plienku, takže PVC nohavičky sa odporúčajú ak sa očakáva 4 a viac pomočení pre túto plienku',
      'Vyzerá, že plienka sa buď premenovala alebo sa už vyrába pod značkou Fabine a nie Rearz, pretože v pôvodnej objednávke je napísené, že produkt už nie je k dispozícii.',
    ],
  },
]
